name: Sanity Dataset Backup
on:
  schedule:
    # Run at 5 past 10 every friday
    # - cron: '0 19 * * 5'
    # Run every 10 minutes
    - cron: '*/10 * * * *'
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Backup dataset
    # defaults:
    #   run:
    #     working-directory: src/lib/config/sanity
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.4
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_BACKUP_TOKEN }}
        with:
          args: . dataset export production backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: production
          path: /backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
          retention-days: 5
