name: Sanity Dataset Backup
on:
  schedule:
    # Run every 5 days at 07.00 GMT
    # - cron: '0 7 */5 * *'
    - cron: '*/10 * * * *'
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Backup dataset
    steps:
      - uses: actions/checkout@v2
      - run: npx @sanity/cli dataset export production backups/backup.tar.gz
        env:
          SANITY_STUDIO_API_PROJECT_ID: ${{ secrets.SANITY_STUDIO_API_PROJECT_ID }}
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_BACKUP_TOKEN }}
      - name: Upload dataset
        uses: actions/upload-artifact@v2
        with:
          name: production
          path: backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
          retention-days: 5
