name: Sanity Dataset Backup
on:
  schedule:
    # Run every 5 days at 07.00 GMT
    # - cron: '0 7 */5 * *'
    - cron: '*/10 * * * *'
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Backup dataset
    defaults:
      run:
        working-directory: src/lib/config/sanity

    steps:
      - uses: actions/checkout@v3
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.3
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_BACKUP_TOKEN }}
        with:
          args: studio dataset export production backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@2
        with:
          name: production-tarball
          path: src/lib/config/sanity/backups/backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
          retention-days: 5
